### ISSUE TITLE
매개변수의 값을 배열로 받아 곱하기

### ISSUE THREAD

**Issue by soheeoott** [soheeoott/java#31]
### 클래스 메소드
```java
public class Calculator {
     int mul(int ... values) {
          int result = 0;
          for(int i = 0; i < values.length; i++) {
               for(int j = i+1; j < values.length; j++) {
                    result = values[i] * values[j];
                    System.out.println("mul 순회 : " + result);
               }
          }
          return result;
     }
}
```
클래스안 `mul` 메소드에 매개변수의 값을 배열`(int ... values)` 로 주어 배열안에 있는 값끼리 곱셈을 수행하는 코드입니다.
<br/><br/>

### 실행 메소드
```java
public class CalculatorRun {
     public static void main(String[] args) {
          Calculator cal = new Calculator();
          int mul = cal.mul(5, 3, 1);
          System.out.println("mul 연산 결과 : " + mul);
     }
}
```
실행 메소드에 객체를 생성하여 매개변수`(5, 3, 1)`로 값을 넣어준 코드입니다.
<br/><br/>

### 결과
실행을 하면
```
mul 순회 : 15
mul 순회 : 5
mul 순회 : 3
mul 연산 결과 : 3
```
`5 * 3 * 1 = 15` 인데, 3 이 담겨져서 리턴됩니다.. ㅠㅠ
<br/><br/>

값이 누적되지 않아서 `result = values[i] * values[j];` 이 부분이 문제인 것 같아
대입 연산자`+=`로 `result += values[i] * values[j];` 바꾸어 주었더니...

```java
for(int j = i+1; j < values.length; j++) {
    result += values[i] * values[j];
    System.out.println("mul 순회 : " + result);
}
```

이런 결과값이 나왔습니다................... 😭😭
```
mul 순회 : 0
mul 순회 : 15
mul 순회 : 20
mul 연산 결과 : 23
```

**Comment by JuHyun419** [comment]
위 mul() 메소드에서 result의 최종값인 3이 리턴됩니다!

![image](https://user-images.githubusercontent.com/50076031/121443501-9081cd00-c9c8-11eb-85fc-30c9df0f9f7a.png)

위 사진에서 j는 i+1부터 시작하니까 i와 j의 값은 다음과 같습니다!

i가 0일때
  - j = 1, result = 15
  - j = 2, result = 5

i가 1일때
  - j = 2, result = 3
  - j = 3(인덱스 범위를 벗어나므로 종료)

i가 2일때
  - j =3(마찬가지로 인덱스 범위를 벗어나므로 종료)

따라서 출력은 15, 5, 3 순서대로 되고 가장 마지막 값인 3이 반환됩니다!

아래 변경하신거는 15+5+3을 리턴해서 23이 리턴이 된겁니당 :)

원하시는 5 * 3 * 1 을 하고자하면 2차원이 아니구 1차원 for문을돌려서 result *= values[i]와 같은 방식으로 하면 될 것 같아요!

+ 디버깅 하는 방법에 대해 찾아보시면 원하는 결과가 나오지 않을때 좀 더 쉽게 찾으실 수 있을것 같아요! 
그리구 해당 연산에 대해 하나씩 적어보시면서 결과를 유추하시는 것도 도움이 될 것 같습니당!

**Comment by soheeoott** [comment]
> 위 mul() 메소드에서 result의 최종값인 3이 리턴됩니다!
> 
> ![image](https://user-images.githubusercontent.com/50076031/121443501-9081cd00-c9c8-11eb-85fc-30c9df0f9f7a.png)
> 
> 위 사진에서 j는 i+1부터 시작하니까 i와 j의 값은 다음과 같습니다!
> 
> i가 0일때
> 
> * j = 1, result = 15
> * j = 2, result = 5
> 
> i가 1일때
> 
> * j = 2, result = 3
> * j = 3(인덱스 범위를 벗어나므로 종료)
> 
> i가 2일때
> 
> * j =3(마찬가지로 인덱스 범위를 벗어나므로 종료)
> 
> 따라서 출력은 15, 5, 3 순서대로 되고 가장 마지막 값인 3이 반환됩니다!
> 
> 아래 변경하신거는 15+5+3을 리턴해서 23이 리턴이 된겁니당 :)
> 
> 원하시는 5 * 3 * 1 을 하고자하면 2차원이 아니구 1차원 for문을돌려서 result *= values[i]와 같은 방식으로 하면 될 것 같아요!
> 
> * 디버깅 하는 방법에 대해 찾아보시면 원하는 결과가 나오지 않을때 좀 더 쉽게 찾으실 수 있을것 같아요!
>   그리구 해당 연산에 대해 하나씩 적어보시면서 결과를 유추하시는 것도 도움이 될 것 같습니당!

구구단 연산처럼 이중 for 문을 돌려서 원소끼리 곱하려고 했는데 잘못된 방법이었네요!! 답변 감사드립니다!!
